name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

# Gives the script permission to update and deploy files to GitHub Pages
permissions:
  contents: write

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        env:
          CI: false
        run: npm run build # Note: If using Vite, make sure your folder is 'dist' below

      # === THE DEPLOYMENT STEP ===
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build # Path to your built files (Change to frontend/dist if using Vite)
          branch: gh-pages # The branch the robot will deploy the files to
